version: '3'

services:
  huohuo-email-assistant:
    build: .
    container_name: huohuo-email-assistant
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "8765:8765"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      - TZ=Asia/Shanghai
      - HOST=0.0.0.0
      - FLASK_PORT=5000
      - WS_PORT=8765
      - JWT_SECRET_KEY=huohuo_email_secret_key
      - ALLOW_REGISTER=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 